"""empty message

Revision ID: 91450ffd8ac8
Revises: 1bd957459b90
Create Date: 2018-01-11 15:35:58.490825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91450ffd8ac8'
down_revision = '1bd957459b90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'created_at')
    # ### end Alembic commands ###
